#!/bin/bash
#
### BEGIN INIT INFO
# Provides: prepare-dirs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Required-Start:
# Required-Stop:
# Short-Description: Create needed directories on /var/log/ for tmpfs at startup
# Description: Create needed directories on /var/log/ for tmpfs at startup
### END INIT INFO
# needed Dirs
DIR[0]=/var/log/apt
DIR[1]=/var/log/ConsoleKit
DIR[2]=/var/log/fsck
DIR[3]=/var/log/ntpstats
DIR[4]=/var/log/lastlog
DIR[5]=/var/log/watchdog
DIR[6]=/var/log/proftpd
case "${1:-''}" in
  start)
  typeset -i i=0 max=${#DIR[*]}
  while (( i < max ))
  do
  mkdir ${DIR[$i]}
  chmod 755 ${DIR[$i]}
  i=i+1
  done
  # set rights
  chown www-data.www-data ${DIR[0]}
  ;;
  stop)
  ;;
  restart)
  ;;
  reload|force-reload)
  ;;
  status)
  ;;
  *)
  echo "Usage: $SELF start"
  exit 1
  ;;
esac
